name: CI
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loilo-inc/actions-loilo-flow-release@main
        with:
          github-repository: ${{ github.repository }}
          github-token: ${{ github.token }}
          github-ref: ${{ github.ref }}
